### ISSUE TITLE
Azimuth tipping point

### ISSUE THREAD

**Issue by mikr0012** [apacha/sensor-fusion-demo#4]
Hey guys,

we are using your sensor fusion code in a project focusing on 360 degree video. It is working very well, however we have a pretty big problem. When using our app, the users are usually holding their phones in an upright position (portrait mode, almost exactly 90 degree tilt). The problem is, that the azimuth will "flip" when tilting a bit back and forth around 90 degrees (e.g. the azimuth ist 100° at tilt 90° and 280° at tilt 91°). We understand that this happens due to the orientation of the magnetic compass in the device. But is there any way to avoid this "compass flipping" around 90° tilt? For us it would even be sufficient if the "tipping point" would be at a bigger tilt angle like 120° such that the user would have to tilt the upper part of the phone about 30° towards the users head before the compass would "flip" (which we assume our users won't do). 

Do you see any chance of achieving this? We saw that the demo actually has a much more stable azimuth than we do, even though we make use of your sensor fusion code. Maybe it is the parameters in the Sensorprovider that need to be set differently?

Any help would be very much appreciated.

Cheers
Micha

**Comment by apacha** [comment]
Hi Micha,

I guess you can fix the 'flipping' point issue, by using a different representation. Any representation that defines rotation around three axes like Euler-Angles are inherently ambiguous, because there are multiple combinations of the same orientation. So my suggestion would be to use a different representation of the orientation, e.g. Quaternions, Rotation Vector or a Rotation Matrix. The repository contains methods for obtaining the device rotation in those representations.

Let me know if this helps.

Cheers,
Alex

**Comment by mikr0012** [comment]
Hi Alex, 

thanks for the quick reply. You are right. Currently we are using Euler-Angles. For our App we need to know the angle of the magnetic compass or at least a relative angle when the user is turning while holding the phone in portrait position. Unfortunately I don't understand much about the math behind. Can we derive the relevant angle from Quaternions, Rotation Vectors or the Rotation Matrix? We don't care about the other axis' angles. But the one related to the magnetic compass is very important to us. 

Currently we do this to calculate the heading:

float[] orientation = new float[3];
orientationProvider.getEulerAngles(orientation);
double heading = mod(orientation[0] + TWO_PI,TWO_PI);
double normHeading = heading / TWO_PI * 360;

Maybe you have an idea how we can achieve the same result but without the "tipping problem"?

Thank you very much for your support!

Cheers,
Micha

**Comment by mikr0012** [comment]
Hi Alex,

I have read a lot about quaternions. So I understand the basic problem of the gimbal lock (which I called compass tipping). However, I did not manage to find any implementation or explanation that would allow me to build a stable compass which we need for our app. There are apps out there that solve the problem. Like the Physics Toolbox: https://play.google.com/store/apps/details?id=com.chrystianvieyra.physicstoolboxsuite&hl=de . Unfortunately I can't figure out how to get from Quaternions to a stable compass reading. Any hint would be very much appreciated.

Thank you very much!

Cheers,
Micha

**Comment by apacha** [comment]
Well... the Quaternions are used to draw the cube, so what exactly are you attempting or what is the issue? I also quickly googled and found these resources that might help you: https://stackoverflow.com/questions/18073680/how-to-get-a-phones-azimuth-with-compass-readings-and-gyroscope-readings, and https://www.sjbaker.org/steve/omniv/eulers_are_evil.html

I've just tried the Physics Toolbox and it suffers from exactly the same issue... Flip your phone in Portrait mode upside down and North does not follow correctly...

If the heading is all you need, getting that should be manageable. Otherwise I would suggest that you use Rotation Matrices, Rotation Vectors or Quaternions for your entire application and do not convert it anywhere to Euler Angles. This app already provides you with Rotation matrix and Quaternions: https://github.com/apacha/sensor-fusion-demo/blob/master/app/src/main/java/org/hitlabnz/sensor_fusion_demo/orientationProvider/OrientationProvider.java

**Comment by mikr0012** [comment]
Hi Alex,

thanks for the explanation. We really only need a stable headings reading that will not flip when pointing the device upwards. I know it does that because of gimbal lock and also because the upper part of the phone seems to taken as the relevant direction for the compass heading. 

We are building an app to capture and play 360 Video on any Smartphone (iOS and Android). For that, we need a precise heading information. We get that from the iPhone which (from my understanding)v features two separate gyroscopes or electronic compasses and hence does deliver a perfect and very stable heading information. We are just trying to get the heading right because otherwise the recording and playback of our videos stutters. I would send you the current APK so you can see what I mean. But for that we need a different communication channel. ;-)

Thank you very much.
Micha

PS Thanks for the links. I'll try to figure out, whether they can help us.

**Comment by apacha** [comment]
If you are only interested in the heading, you may detect the orientation of the device first, and then convert the quaternion to Euler angles with respect to the device orientation and only obtain the first of the three angles. Note that depending on whether you are portrait or landscape mode, you have to make the calculation in the right order. Please refer to the above provided links and other resources on the internet, of which there are plenty.

I wish you all the best with you application.

**Comment by mikr0012** [comment]
Hi Alex,

found a fix. We used orientationProvider.getEulerAngles(orientation); Now we get the quaternion first orientationProvider.getQuaternion(q); and then we use orientation = q.toEulerAngles(); That did the trick. Don't get it. But now the gimbal lock is gone.

Best wishes and thank you very much for your support!
Micha
