### ISSUE TITLE
about slerp

### ISSUE THREAD

**Issue by XNPY** [apacha/sensor-fusion-demo#6]
why weight should be close to 1   and why the rotation will be more accure after slerp

**Comment by apacha** [comment]
Hi xnpy, I am afraid that I do not understand your question. Can you elaborate a little more, please?

**Comment by XNPY** [comment]
1st question form your code: /**This weight determines directly how much the rotation sensor will be used to correct (inSensor-fusion-scenario 1 - SensorSelection.GyroscopeAndRotationVector). Must be a value between 0 and 1.0 means that the system entirely relies on the gyroscope, whereas 1 means that the system relies entirely onthe rotationVector.*/
    private static final float DIRECT_INTERPOLATION_WEIGHT = 0.005f; 
I want to know why DIRECT_INTERPOLATION_WEIGHT choose 0.005
second：why use Spherical linear Interpolation to fusion gyroscope and rotation vector,in other words,why orientation after SLERP perform better than gyroscope and rotation vector,What's the mechanism about this .
Thank you very much for your reply.

**Comment by apacha** [comment]
I see. The first value simply determines how much to use the Gyroscope and Rotation Vector. Think of it as a slider. Any value between 0 and 1 is valid. 0.5 would take half of Gyroscope and half of the rotation vector. Now since the rotation vector is only used to initialize and correct, its influence was empirically set to a low number. There is no science behind 0.005f.  You may try completely different numbers to see how it works for you.

Why SLERP? Well, the rotations from both sensors are stored in quaternions. Now you have two vectors in a four-dimensional space (quaternions) and you simply want to do something like an 'average' between them. SLERP is doing exactly that, plus it lets you determine how much you want to interpolate between the two vectors. See https://en.wikipedia.org/wiki/Slerp

The main reasoning was that the gyroscope was more stable and responsive, why the rotation vector was correct in terms of absolute orientation. So I'm using mostly the gyroscope and only slightly correcting for drift with the rotation vector, if you will. 

Hope this answers your question.

**Comment by XNPY** [comment]
Your answer is of great help to me，thank you very much.
